name: _diag-trivy
on:
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
  actions: read
  packages: read
jobs:
  diag-trivy:
    uses: attested-delivery/.github/.github/workflows/reusable-trivy.yml@94e7410b9fad3498a1e507807900edbd2269ef81
    with:
      scan-iac: true
